version: "3.7"
services:

  postgres:
    build: ./postgreSQL-image
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=init_db
      - PGPASSWORD=root
  pgadmin:
    hostname: pgUI
    container_name: pgUI
    user: root 
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  debezium:
    image: debezium/connect:1.5  
    hostname: debezium
    container_name: debezium
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
    depends_on: [kafka]
    ports:
      - 8083:8083
  

  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_ADVERTISED_LISTENERS:PLAINTEXT://kafka:9092


  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafkaUI
    container_name: kafkaUI
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka

  hudi:
    image: apachehudi/hudi-hadoop_3.1.0-hive_3.1.2-sparkbase_3.2.1
    hostname: hudi
    container_name: hudi
    environment:
      - CLUSTER_NAME=hudi_hadoop310_hive312_spark321
      - SPARK_MASTER_HOST=localhost
    volumes:
      - C:\Users\arthu\cloudera-files:/hadoop-data
    depends_on:
      - kafka
    ports:
      - "8020:8020"
      - "5005"
      - 8080:8080
      - 7077:7077
      - 8081:8081  
      - 4041:4040
      - 34813:34813

  pyspark:
    image: jupyter/pyspark-notebook:latest
    hostname: pyspark
    container_name: pyspark
    ports:
      - 8888:8888
    depends_on:
      - kafka
      - hudi
